/**
 * Created by lucky on 18.03.19.
 */

export default {
  data: {
    getData: 'GetData',
    setData: 'SetData',
  },
  org: {
    create: 'Create',
    remove: 'Remove',
    getInfo: 'GetInfo',
    setInfo: 'SetInfo',
    getStatus: 'GetStatus',
    changeStatus: 'ChangeStatus',
  },
  usr: {
    getProfile: 'GetProfile',
    getProfiles: 'GetProfiles',
    setProfile: 'SetProfile',
    removeAccount: 'RemoveAccount',
    disableAccount: 'DisableAccount',
    enableAccount: 'EnableAccount',
    createAccount: 'CreateAccount',
    login: 'Login',
    checkAuthToken: 'CheckAuthToken',
    getAuthScheme: 'GetAuthScheme',
    confirmUserAction: 'ConfirmUserAction',
    getAccountStatus: 'GetAccountStatus',
    getProfilesByRole: 'GetProfilesByRole',
    activateAccount: 'ActivateAccount',
    restorePassword: 'RestorePassword',
    changePassword: 'ChangePassword',
  },
  msg: {
    // System functions
    createAdminAccess: 'CreateAdminAccess',
    // Group 2 Admins function
    addNewAccount: 'AddNewAccount',
    // ----------Access rules
    changeDefaultUserGroup: 'ChangeDefaultUserGroup',
    changeDefaultAgentGroup: 'ChangeDefaultAgentGroup',
    changeDefaultUserMode: 'ChangeDefaultUserMode',
    changeDefaultAgentMode: 'ChangeDefaultAgentMode',
    changeMessageUserMode: 'ChangeMessageUserMode',
    changeMessageAgentMode: 'ChangeMessageAgentMode',
    changeMessageUserOwner: 'ChangeMessageUserOwner',
    changeMessageUserGroup: 'ChangeMessageUserGroup',
    changeMessageAgentOwner: 'ChangeMessageAgentOwner',
    changeMessageAgentGroup: 'ChangeMessageAgentGroup',
    // Organization structure
    createDepartment: 'CreateDepartment',
    removeDepartment: 'RemoveDepartment',
    renameDepartment: 'RenameDepartment',
    getDepartments: 'GetDepartments',
    getMembershipInDepartment: 'GetMembershipInDepartment',
    addUserToDepartment: 'AddUserToDepartment',
    removeUserFromDepartment: 'RemoveUserFromDepartment',
    // Type 4 Message managing
    changeMessageAgent: 'ChangeMessageAgent',
    countFilterMessages: 'CountFilterMessages',
    changeMessageCaption: 'ChangeMessageCaption',
    addTextToDraftComment: 'AddTextToDraftComment',
    getDraftComment: 'GetDraftComment',
    submitDraftComment: 'SubmitDraftComment',
    addNewMessage: 'AddNewMessage',
    addNewTextMessage: 'AddNewTextMessage',
    addNewGroupMessage: 'AddNewGroupMessage',
    addNewDraftMessage: 'AddNewDraftMessage',
    addNewDraftComment: 'AddNewDraftComment',
    createMessageNote: 'CreateMessageNote',
    submitDraftNote: 'SubmitDraftNote',
    addAttachmentToDraftComment: 'AddAttachmentToDraftComment',
    removeAttachmentFromComment: 'RemoveAttachmentFromComment',
    rejectDraftComment: 'RejectDraftComment',
    selectOwnMessages: 'SelectOwnMessages',
    selectMessages: 'SelectMessages',
    // selectFilterMessages: 'SelectFilterMessages',
    selectGroupMessages: 'SelectGroupMessages',
    selectAllGroupMessages: 'SelectAllGroupMessages',
    addNewComment: 'AddNewComment',
    selectComments: 'SelectComments',
    getCommentAttachment: 'GetCommentAttachment',
    closeMessage: 'CloseMessage',
    changeAgentMessage: 'ChangeAgentMessage', // MessageAgent
    addNewHiddenComment: 'AddNewHiddenComment',
    getMessage: 'GetMessage',
    removeCommentAttachment: 'RemoveCommentAttachment',
    changeMessagePriority: 'ChangeMessagePriority',
  },
};
